imports:
    - { resource: parameters.ini }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enabled: true, enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale: %locale%
    session:
        name: aalf_crf
        

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    form:
        resources:
            - ':Form:theme.html.twig'

# Assetic Configuration
assetic:
    debug: %kernel.debug%
    use_controller: false
    filters:
        uglifyjs2:
            bin: %uglifyjs2_path%
        cssrewrite: ~ 
        uglifycss:
            bin: %uglifycss_path%

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset: %charset%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    port:      %mailer_port%

fos_user:
    db_driver:     orm                        # Le type de BDD à utiliser, nous utilisons l'ORM Doctrine depuis le début
    firewall_name: main                       # Le nom du firewall derrière lequel on utilisera ces utilisateurs
    user_class:    Virgule\Bundle\MainBundle\Entity\Teacher # La classe de l'entité User que nous utilisons
    
jms_security_extra:
    secure_all_services: false

siphoc_pdf:
    basepath: "%kernel.root_dir%/../web"
    binary: "%wkhtmltopdf_path%"
    options:
        'lowquality': false
        'enable-javascript': false
        'debug-javascript': false
