VirguleMainBundle:
    resource: "@VirguleMainBundle/Controller/"
    type:     annotation
    prefix:   /virgule

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
