virgule_main_bundle_security:
    resource: "@VirguleSecurityBundle/Controller/"
    type:     annotation
    prefix:   /

virgule_main_bundle:
    resource: "@VirguleMainBundle/Controller/"
    type:     annotation
    prefix:   /
    
login_check:
    pattern:   /login_check
