security:
    acl:
        connection: default
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Virgule\Bundle\MainBundle\Entity\Formateurs: plaintext

    role_hierarchy:
        ROLE_USER:        ROLE_VIEWER
        ROLE_SECRETARY:   ROLE_USER
        ROLE_ADMIN:       ROLE_SECRETARY
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity: { class: Virgule\Bundle\MainBundle\Entity\Formateurs, property: login }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/virgule/login$
            security: false
            anonymous: false

        secured_area:
            pattern:    ^/virgule
            anonymous: false
            form_login:
                login_path:  /virgule/login
                check_path:  /virgule/login_check
            logout:
                path:   /virgule/logout
                target: /virgule/login
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
