security:
    acl:
        connection: default
    encoders:
        Virgule\Bundle\MainBundle\Entity\Teacher: plaintext

    role_hierarchy:
        ROLE_USER:        ROLE_GUEST
        ROLE_SECRETARY:   ROLE_USER
        ROLE_SUPER_SECRETARY: ROLE_SECRETARY
        ROLE_ADMIN:       ROLE_SECRETARY
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity: { class: Virgule\Bundle\MainBundle\Entity\Teacher, property: username }

    firewalls:            
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/login$
            security: false
            anonymous: false

        secured_area:
            pattern:    /
            anonymous: false
            form_login:
                login_path:  /login
                check_path:  /login_check
            logout:
                path:   /logout
                target: /login
            anonymous: false
            #http_basic:
            #    realm: "Secured Demo Area"
            remember_me:
                key:      "%secret%"
                lifetime: 2592000 # 30 days in seconds
                path:     /
                domain:   ~ # Defaults to the current domain from $_SERVER

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
