## YAML Template.
---
teacher_index:
    pattern:   /teacher/
    defaults:  { _controller: VirguleMainBundle:Teacher:index }
teacher_update:
    pattern:    /teacher/{id}/edit
    defaults:  { _controller: VirguleMainBundle:Teacher:edit }
teacher_show:
    pattern:    /teacher/{id}/show
    defaults:  { _controller: VirguleMainBundle:Teacher:show }
    